# Generated by Django 5.1.5 on 2025-01-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0003_orderserviceprovider_alter_order_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
