# Generated by Django 5.1.5 on 2025-01-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0004_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='to_be_shipped',
        ),
    ]
