# Generated by Django 5.1.5 on 2025-01-25 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0007_rename_orderstatus_orderdeliveryaddressstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpaymentstatus',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='orderpaymentstatus',
            name='payment_date',
        ),
        migrations.CreateModel(
            name='OderPayment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_manager.order')),
            ],
            options={
                'verbose_name_plural': 'order payments',
                'db_table': 'order_payment',
            },
        ),
    ]
