# Generated by Django 5.1.5 on 2025-01-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0009_alter_orderpaymentstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qty_measurement_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
