# Generated by Django 5.1.5 on 2025-01-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0010_orderitem_qty_measurement_unit'),
        ('shared', '0002_measumentsunits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='qty_measurement_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.measumentsunits'),
        ),
    ]
