# Generated by Django 5.1.5 on 2025-01-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0011_alter_orderitem_qty_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
