# Generated by Django 5.1.5 on 2025-01-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0012_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oderpayment',
            name='order',
        ),
        migrations.AddField(
            model_name='oderpayment',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_manager.orderitem'),
        ),
    ]
