# Generated by Django 5.0.7 on 2025-02-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0014_remove_orderpaymentstatus_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
